services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - storage_uploads:/var/www/html/storage/app/public

volumes:
  storage_uploads:
